In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Extract
df = pd.read_csv('open_data.zip')
print("Original Data:\n", df.head())

# Transform - Handle missing values
df.fillna(df.mean(numeric_only=True), inplace=True)
for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Transform - Encode categorical columns
label_encoders = {}
for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Transform - Feature scaling
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Split data
target = 'transmission'
X = df.drop(target, axis=1)
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Load - Save transformed data
cleaned_df = pd.concat([X, y], axis=1)
cleaned_df.to_csv('cleaned_data.csv', index=False)
print("ETL Process Completed.")

Original Data:
    year   make                model        trim   body transmission  \
0  2015    Kia              Sorento          LX    SUV    automatic
1  2015    Kia              Sorento          LX    SUV    automatic
2  2014    BMW             3 Series  328i SULEV  Sedan    automatic
3  2015  Volvo                  S60          T5  Sedan    automatic
4  2014    BMW  6 Series Gran Coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

/tmp/ipython-input-6-3561442576.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

ETL Process Completed.